### ISSUE TITLE
It's to avoid using awful domain registry search engine of AfraidDNS to get a text list that we can search ourself?

### ISSUE THREAD

**Issue by bphd** [encratite/AfraidParser#1]

**Comment by encratite** [comment]
I have absolutely no idea what this code does. As you can see it's over 14 years old. I stopped using Haskell ages ago, too.

**Comment by bphd** [comment]
> I have absolutely no idea what this code does. As you can see it's over 14 years old. I stopped using Haskell ages ago, too.

You are definitely a true developer
